FROM python:latest
EXPOSE 8880
WORKDIR /nklf1
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN mkdir /nklf1/app/
RUN mkdir /nklf1/app/templates/
COPY main.py /nklf1/
COPY app.wsgi /nklf1/
COPY app/* /nklf1/app/
COPY app/templates/* /nklf1/app/templates/
COPY .env /nklf1/app/
CMD ["python", "main.py"]
#CMD ["flask", "run", "--host", "0.0.0.0:8880"]
#CMD ["gunicorn", "--bind", "0.0.0.0:8880", "app::create_app()"]
