FROM ubuntu:latest
WORKDIR /srv
#COPY requirements.txt .
RUN apt-get update 
RUN apt-get -y upgrade

RUN apt-get -y install python3
RUN apt-get -y install python3-flask python3-wtforms python3-flaskext.wtf python3-numpy python3-dotenv

RUN apt-get -y install apache2
RUN apt-get -y install libapache2-mod-wsgi-py3
RUN apt-get clean

ENV APACHE_RUN_USER=www-data
ENV APACHE_RUN_GROUP=www-data
ENV APACHE_LOG_DIR=/var/log/apache2
ENV SECRET_KEY=INSERTYOURSECRETKEY

COPY app.wsgi /srv/
RUN mkdir /srv/app/
COPY app/* /srv/app/

RUN mkdir /srv/app/templates
COPY templates/* /srv/app/templates/
RUN mkdir /srv/app/static
COPY static/* /srv/app/static/
COPY apache2.conf /etc/apache2/apache2.conf
#RUN mv /app/apache2.conf /etc/apache2/apache2.conf
#RUN ln -s /app /usr/local/lib/python3.6/dist-packages/app
#RUN ln -s /app /usr/local/lib/python3.12/dist-packages/app
RUN chown www-data:www-data /srv/*
RUN chown www-data:www-data /srv/app/*
RUN chown www-data:www-data /srv/app/templates
RUN chown www-data:www-data /srv/app/static

CMD ["apache2ctl", "-D", "FOREGROUND", "-e", "debug"]
EXPOSE 80
